export { default as Hero } from "./hero.svelte";
export { default as HaveAnyQuestions } from "../../../sections/haveAnyQuestions.svelte";
export { default as WhatIsTLIP } from "./whatIsTLIP.svelte";
export { default as WhyTLIP } from "./whyTLIP.svelte";
export { default as Benefits } from "./benefits.svelte";
export { default as Technology } from "./technology.svelte";
export { default as HowDoesTLIPWork } from "./howDoesTLIPWork.svelte";
export { default as WhoAreWe } from "./whoAreWe.svelte";
export { default as UkEcosystem } from "./ukEcosystem.svelte";
